### ISSUE TITLE
Level 5 and 6 missing?

### ISSUE THREAD

**Issue by goreil** [pwncollege/babyauto-crackmes#1]
Hi, I love these challenges!

I'm not seeing level 5 and level 6, is that intended?

**Comment by goreil** [comment]
For example level 5 requires "/opt/all-binutils/inst/2.11/readelf". Is "https://ftp.gnu.org/gnu/binutils/binutils-2.11.tar.gz" the correct one?

**Comment by zardus** [comment]
IIRC, levels 5 and 6 used binaries from this repo: https://github.com/pwncollege/all-binutils

Sorry about the confusion! My goal is to bring this module back into the Archived dojo in pwncollege, so hopefully you'll be able to tackle it "for real" soon :-)
